version: '3.8'

services:
  backend:
    build: 
      context: ./backend/api_node/
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8080:3001"
    volumes:
      - ./backend/api_node:/usr/src/app
      - ./.env:/usr/src/app/.env 
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/shopper_chalenger/
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "80:3000"
    volumes:
      
      - ./.env:/usr/src/app/.env 
     
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
